[build]
  command = "ng build --configuration production"
  publish = "dist/web/browser"

[[edge_functions]]
  path = "/card/*"
  function = "meta-tags"

[[redirects]]
  from = "/card/*"
  to = "/.netlify/functions/meta-tags"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200