[build]
  command = "ng build --configuration production"
  publish = "dist/web/browser"

[[edge_functions]]
  path = "/card-meta/*"
  function = "meta-tags"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200